import '../utils/key_code.dart';
// https://github.com/jtroo/kanata/blob/a9dabfcb07e22c9efa0bc15349780b10afacb6cd/parser/src/keys/mod.rs as guide

class Mappings {
  static const Map<String, String> keyMappings = {
    '◄': 'Left',
    '←': 'Left',
    '◀': 'Left',
    'LEFT': 'Left',
    '▲': 'Up',
    '↑': 'Up',
    'UP': 'Up',
    '►': 'Right',
    '→': 'Right',
    '▶': 'Right',
    'RIGHT': 'Right',
    '▼': 'Down',
    '↓': 'Down',
    'DOWN': 'Down',
    '⏎': 'Enter',
    '↵': 'Enter',
    '↩': 'Enter',
    '⌤': 'Enter',
    '␤': 'Enter',
    'ENTER': 'Enter',
    'ENT': 'Enter',
    'RETURN': 'Enter',
    'RET': 'Enter',
    '⌫': 'Backspace',
    '␈': 'Backspace',
    'BSPC': 'Backspace',
    'BS': 'Backspace',
    'BKSP': 'Backspace',
    'BKS': 'Backspace',
    '⌦': 'Delete',
    '␡': 'Delete',
    'DEL': 'Delete',
    'DELETE': 'Delete',
    '⭾': 'Tab',
    '↹': 'Tab',
    'TAB': 'Tab',
    '␣': ' ',
    '⎵': ' ',
    '␠': ' ',
    'SPC': ' ',
    'SPACE': ' ',
    '⎋': 'Escape',
    'ESC': 'Escape',
    '⇪': 'CapsLock',
    'CAPS': 'CapsLock',
    '⤓': 'PageDown',
    '⇟': 'PageDown',
    'PGDN': 'PageDown',
    '⤒': 'PageUp',
    '⇞': 'PageUp',
    'PGUP': 'PageUp',
    '⇱': 'Home',
    '⇤': 'Home',
    '↖': 'Home',
    'HOME': 'Home',
    '⇲': 'End',
    '⇥': 'End',
    '↘': 'End',
    'END': 'End',
    // Treating VK_(modifier) as default VK_(left modifier) for now
    // '⇧': 'Shift',
    // 'SFT': 'Shift',
    // 'SHFT': 'Shift',
    // 'SHIFT': 'Shift',
    '⇧': 'LShift',
    'SFT': 'LShift',
    'SHFT': 'LShift',
    'SHIFT': 'LShift',
    '‹⇧': 'LShift',
    'LSFT': 'LShift',
    'LSHFT': 'LShift',
    'LSHIFT': 'LShift',
    '⇧›': 'RShift',
    'RSFT': 'RShift',
    'RSHFT': 'RShift',
    'RSHIFT': 'RShift',
    // '⌃': 'Control',
    // '⎈': 'Control',
    // 'CTL': 'Control',
    // 'CTRL': 'Control',
    '⌃': 'LControl',
    '⎈': 'LControl',
    'CTL': 'LControl',
    'CTRL': 'LControl',
    '‹⌃': 'LControl',
    '‹⎈': 'LControl',
    'LCTL': 'LControl',
    'LCTRL': 'LControl',
    // '⌥': 'Alt',
    // '⎇': 'Alt',
    // 'ALT': 'Alt',
    '⌥': 'LAlt',
    '⎇': 'LAlt',
    'ALT': 'LAlt',
    '‹⎇': 'LAlt',
    '‹⌥': 'LAlt',
    'LALT': 'LAlt',
    '⎇›': 'RAlt',
    '⌥›': 'RAlt',
    'RALT': 'RAlt',
    '⌃›': 'RControl',
    '⎈›': 'RControl',
    'RCTL': 'RControl',
    'RCTRL': 'RControl',
    '⌘': 'Win',
    '⊞': 'Win',
    '◆': 'Win',
    '❖': 'Win',
    'WIN': 'Win',
    '⎀': 'Insert',
    'INS': 'Insert',
    'INSERT': 'Insert',
    '🔢₀': '0',
    '🔢₁': '1',
    '🔢₂': '2',
    '🔢₃': '3',
    '🔢₄': '4',
    '🔢₅': '5',
    '🔢₆': '6',
    '🔢₇': '7',
    '🔢₈': '8',
    '🔢₉': '9',
    '🔢⁄': '/',
    '🔢₊': '+',
    '🔢∗': '*',
    '🔢₋': '-',
    '🔢．': '.',
    '⇭': 'NumLock',
    'NLK': 'NumLock',
    'NLCK': 'NumLock',
    '⇳🔒': 'ScrollLock',
    'SLCK': 'ScrollLock',
    'SCRLCK': 'ScrollLock',
    '‐': '-',
    '₌': '='
  };
  static String getKeyForSymbol(String symbol) {
    return keyMappings[symbol] ?? symbol;
  }

  static String? getShiftedSymbol(String symbol) {
    for (final entry in activeKeyCodeShiftMap.entries) {
      final key = entry.key;
      if (key.$2 == false) {
        final shifted = activeKeyCodeShiftMap[(key.$1, true)];
        if (entry.value == symbol && shifted != null) {
          return shifted;
        }
      }
    }
    return symbol;
  }
}
