// https://github.com/jtroo/kanata/blob/a9dabfcb07e22c9efa0bc15349780b10afacb6cd/parser/src/keys/mod.rs as guide

class SymbolMappings {
  static const Map<String, String> keyMappings = {
    '◄': 'Left',
    '←': 'Left',
    '◀': 'Left',
    '▲': 'Up',
    '↑': 'Up',
    '►': 'Right',
    '→': 'Right',
    '▶': 'Right',
    '▼': 'Down',
    '↓': 'Down',
    '⏎': 'Enter',
    '↵': 'Enter',
    '↩': 'Enter',
    '⌤': 'Enter',
    '␤': 'Enter',
    '⌫': 'Backspace',
    '␈': 'Backspace',
    '⌦': 'Delete',
    '␡': 'Delete',
    '⭾': 'Tab',
    '↹': 'Tab',
    '␣': ' ',
    '⎵': ' ',
    '␠': ' ',
    '⌘': 'Win',
    '⊞': 'Win',
    '◆': 'Win',
    '❖': 'Win',
    '⌥': 'Alt',
    '⎇': 'Alt',
    '⎋': 'Escape',
    '⇪': 'CapsLock',
    '⤓': 'PageDown',
    '⇟': 'PageDown',
    '⤒': 'PageUp',
    '⇞': 'PageUp',
    '⇱': 'Home',
    '⇤': 'Home',
    '↖': 'Home',
    '⇲': 'End',
    '⇥': 'End',
    '↘': 'End',
    '⇧': 'Shift',
    '⌃': 'Control',
    '⎈': 'Control',
    '⎀': 'Insert',
    '🔢₀': 'Num0',
    '🔢₁': 'Num1',
    '🔢₂': 'Num2',
    '🔢₃': 'Num3',
    '🔢₄': 'Num4',
    '🔢₅': 'Num5',
    '🔢₆': 'Num6',
    '🔢₇': 'Num7',
    '🔢₈': 'Num8',
    '🔢₉': 'Num9',
    '🔢⁄': 'NumDivide',
    '🔢₊': 'NumAdd',
    '🔢∗': 'NumMultiply',
    '🔢₋': 'NumSubtract',
    '🔢．': 'NumDecimal',
    '⧵': '\\',
    '＼': '\\',
    '⸴': ',',
    '．': '.',
    '⁄': '/',
    '【': '[',
    '「': '[',
    '〔': '[',
    '⎡': '[',
    '】': ']',
    '」': ']',
    '〕': ']',
    '⎣': ']',
    '︔': ';',
    '⇭': 'NumLock',
    '⇳🔒': 'ScrollLock',
    '‐': '-',
    '₌': '='
  };
  static String getKeyForSymbol(String symbol) {
    return keyMappings[symbol] ?? symbol;
  }
}
