final List<String> availableFontFamilies = [
  'Alexandria',
  'Anonymous Pro',
  'Berkeley Mono',
  'Cairo',
  'Cascadia Code',
  'Cascadia Mono',
  'Comic Mono',
  'CommitMono',
  'Consolas',
  'Courier',
  'Courier Prime',
  'Cousine',
  'Dank Mono',
  'DejaVu Sans Mono',
  'DM Mono',
  'Droid Sans Mono',
  'Fantasque Sans Mono',
  'Fira Code',
  'Fira Mono',
  'Geist',
  'GeistMono',
  'Google Sans',
  'Hack',
  'Hasklig',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'Inconsolata',
  'Input',
  'Inter',
  'Iosevka',
  'JetBrains Mono',
  'Liberation Mono',
  'Manrope',
  'Menlo',
  'Meslo',
  'Monaco',
  'Monaspace Argon',
  'Monaspace Krypton',
  'Monaspace Neon',
  'Monaspace Radon',
  'Monaspace Xenon',
  'Monocraft',
  'MonoLisa',
  'mononoki',
  'Montserrat',
  'Noto Sans',
  'Nunito',
  'Open Sans',
  'Operator Mono',
  'Poppins',
  'PT Mono',
  'Readex Pro',
  'Recursive',
  'Roboto',
  'Roboto Mono',
  'Rubik',
  'SF Mono',
  'Source Code Pro',
  'Source Sans Pro',
  'Space Mono',
  'Ubuntu',
  'Ubuntu Mono',
  'Victor Mono',
];
