final List<String> availableFontFamilies = [
  'Berkeley Mono',
  'Cascadia Mono',
  'Comic Mono',
  'CommitMono',
  'Consolas',
  'Courier',
  'Cousine',
  'Dank Mono',
  'DM Mono',
  'Droid Sans Mono',
  'Fira Code',
  'Fira Mono',
  'Geist',
  'GeistMono',
  'Google Sans',
  'Hack',
  'IBM Plex Mono',
  'Inconsolata',
  'Input',
  'Inter',
  'Iosevka',
  'JetBrains Mono',
  'Manrope',
  'Meslo',
  'Monaspace Argon',
  'Monaspace Krypton',
  'Monaspace Neon',
  'Monaspace Radon',
  'Monaspace Xenon',
  'Monocraft',
  'MonoLisa',
  'mononoki',
  'Montserrat',
  'Nunito',
  'Poppins',
  'Roboto',
  'Roboto Mono',
  'Source Code Pro',
  'Source Sans Pro',
  'Ubuntu',
  'Ubuntu Mono',
  'Victor Mono',
];
