import 'package:win32/win32.dart';

// https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
final Map<int, String> _keyCodeMap = {
  VK_A: 'A',
  VK_B: 'B',
  VK_C: 'C',
  VK_D: 'D',
  VK_E: 'E',
  VK_F: 'F',
  VK_G: 'G',
  VK_H: 'H',
  VK_I: 'I',
  VK_J: 'J',
  VK_K: 'K',
  VK_L: 'L',
  VK_M: 'M',
  VK_N: 'N',
  VK_O: 'O',
  VK_P: 'P',
  VK_Q: 'Q',
  VK_R: 'R',
  VK_S: 'S',
  VK_T: 'T',
  VK_U: 'U',
  VK_V: 'V',
  VK_W: 'W',
  VK_X: 'X',
  VK_Y: 'Y',
  VK_Z: 'Z',
  VK_F1: 'F1',
  VK_F2: 'F2',
  VK_F3: 'F3',
  VK_F4: 'F4',
  VK_F5: 'F5',
  VK_F6: 'F6',
  VK_F7: 'F7',
  VK_F8: 'F8',
  VK_F9: 'F9',
  VK_F10: 'F10',
  VK_F11: 'F11',
  VK_F12: 'F12',
  VK_RETURN: 'Enter',
  VK_TAB: 'Tab',
  VK_BACK: 'Backspace',
  VK_ESCAPE: 'Escape',
  VK_DELETE: 'Delete',
  VK_INSERT: 'Insert',
  VK_HOME: 'Home',
  VK_END: 'End',
  VK_PRIOR: 'PageUp',
  VK_NEXT: 'PageDown',
  VK_LEFT: 'Left',
  VK_RIGHT: 'Right',
  VK_UP: 'Up',
  VK_DOWN: 'Down',
  VK_LSHIFT: 'LShift',
  VK_RSHIFT: 'RShift',
  VK_LCONTROL: 'LControl',
  VK_RCONTROL: 'RControl',
  VK_LMENU: 'LAlt',
  VK_RMENU: 'RAlt',
  VK_LWIN: 'Win',
  VK_RWIN: 'RWin',
  VK_CAPITAL: 'CapsLock',
  VK_NUMLOCK: 'NumLock',
  VK_SCROLL: 'ScrollLock',
  VK_SPACE: ' ',
  VK_NUMPAD0: 'Num0',
  VK_NUMPAD1: 'Num1',
  VK_NUMPAD2: 'Num2',
  VK_NUMPAD3: 'Num3',
  VK_NUMPAD4: 'Num4',
  VK_NUMPAD5: 'Num5',
  VK_NUMPAD6: 'Num6',
  VK_NUMPAD7: 'Num7',
  VK_NUMPAD8: 'Num8',
  VK_NUMPAD9: 'Num9',
  VK_MULTIPLY: 'NumMultiply',
  VK_ADD: 'NumAdd',
  VK_SUBTRACT: 'NumSubtract',
  VK_DECIMAL: 'NumDecimal',
  VK_DIVIDE: 'NumDivide',
};

final Map<(int, bool), String> _keyCodeShiftMap = {
  (0x30, false): '0',
  (0x30, true): ')',
  (0x31, false): '1',
  (0x31, true): '!',
  (0x32, false): '2',
  (0x32, true): '@',
  (0x33, false): '3',
  (0x33, true): '#',
  (0x34, false): '4',
  (0x34, true): '\$',
  (0x35, false): '5',
  (0x35, true): '%',
  (0x36, false): '6',
  (0x36, true): '^',
  (0x37, false): '7',
  (0x37, true): '&',
  (0x38, false): '8',
  (0x38, true): '*',
  (0x39, false): '9',
  (0x39, true): '(',
  (VK_OEM_COMMA, false): ',',
  (VK_OEM_COMMA, true): '<',
  (VK_OEM_PERIOD, false): '.',
  (VK_OEM_PERIOD, true): '>',
  (VK_OEM_1, false): ';',
  (VK_OEM_1, true): ':',
  (VK_OEM_2, false): '/',
  (VK_OEM_2, true): '?',
  (VK_OEM_4, false): '[',
  (VK_OEM_4, true): '{',
  (VK_OEM_6, false): ']',
  (VK_OEM_6, true): '}',
  (VK_OEM_5, false): '\\',
  (VK_OEM_5, true): '|',
  (VK_OEM_3, false): '`',
  (VK_OEM_3, true): '~',
  (VK_OEM_7, false): "'",
  (VK_OEM_7, true): '"',
  (VK_OEM_PLUS, false): '=',
  (VK_OEM_PLUS, true): '+',
  (VK_OEM_MINUS, false): '-',
  (VK_OEM_MINUS, true): '_',
};

String getKeyFromKeyCodeShift(int keyCode, bool isShiftDown) {
  final shiftKey = _keyCodeShiftMap[(keyCode, isShiftDown)];
  if (shiftKey != null) return shiftKey;
  final key = _keyCodeMap[keyCode];
  if (key != null) return key;
  return '';
}
